class RewardShaping:
    DAMAGE_REWARD_FACTOR = 0.01
    DISTANCE_REWARD = 5e-4
    DISTANCE_PENALTY = -2.5e-3
    DISTANCE_REWARD_THRESHOLD = 3.0
    AMMO_REWARD_FACTOR = 0.02
    AMMO_PENALTY_FACTOR = -0.01
    HEALTH_REWARD_FACTOR = 0.02
    HEALTH_PENALTY_FACTOR = -0.01
    ARMOR_REWARD_FACTOR = 0.01

REWARD_SHAPING = RewardShaping()